language: ruby
rvm:
    - 2.5.0
# update gems to avoid issues with Bundler 1.16.1 and rubygems 2.7.3
# see https://github.com/travis-ci/travis-ci/issues/8978
before_install: gem update --system
script:
    - bundle exec ruby test/validate.rb
    - bundle exec jekyll build
